services:
  mariadb:
    image: mariadb:11.5.2
    container_name: mariadb_health
    environment:
      MARIADB_ROOT_PASSWORD: qwer1234
      MARIADB_DATABASE: health
    ports:
      - "3308:3306"
    volumes:
      - ./db/:/var/lib/mysql