spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/health
    username: root
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

kakaopay:
  admin-key: ec53f698376a56d2811f339c58a5e25e
  cid: "TC0ONETIME"
  ready-url: "https://localhost/v1/payment/ready"
  approve-url: "https://localhost/v1/payment/approve"

